POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video node teste",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/92407767-4e45-4a03-b90c-d54950d8b1b8
Content-Type: application/json

{
    "title": "Video 02 teste",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

DELETE http://localhost:3333/videos/92407767-4e45-4a03-b90c-d54950d8b1b8